# Generated by Django 5.2.1 on 2025-06-12 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_alter_inputused_options'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputused',
            options={'ordering': ['-date_used'], 'verbose_name': 'Input Used', 'verbose_name_plural': 'Inputs Used'},
        ),
        migrations.RemoveField(
            model_name='inputused',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inputused',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inputused',
            name='amount_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The amount of the inventory item used for this crop', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputused',
            name='inventory_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='inputused',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs_used', to='crops.crop'),
        ),
    ]
